### ISSUE TITLE
Adding DKPro C4Corpus to projects

### ISSUE THREAD

**Issue by habernal** [dkpro/dkpro.github.io#2]
I'd like to add DKPro C4Corpus to the list of projects (btw: where is the `projects.html` which is included in `index.md`?)

**Comment by reckart** [comment]
Edit _data/projects.yml

**Comment by habernal** [comment]
Yep, that's the right place... how about the logo? For example `https://dkpro.github.io/dkpro-lab/assets/img/logo.png` is not under _assets.

**Comment by reckart** [comment]
Not sure what you mean. 

We typically only have logos for those projects that also set up a proper website (gh-pages branch according to our template - https://github.com/dkpro/dkpro-page-template).

For projects that just have a repo page, (e.g. DKPro Keyphrases) we usually don't have a logo.

**Comment by reckart** [comment]
If you want a logo but do not want to set up a gh-pages branch in your project (yet), maybe you could drop the logo into your repo somewhere and then link to it from the projects.xml?

**Comment by habernal** [comment]
Worked smoothly. What is the easiest way to change the default link to the non-existing page ("https://dkpro.github.io/dkpro-c4corpus") to the project github page? ---never mind :)

**Comment by habernal** [comment]
Fixed.
