### ISSUE TITLE
Ask contributors for pull requests, not patches

### ISSUE THREAD

**Issue by logological** [dkpro/dkpro.github.io#6]
Our [instructions for contributing](https://dkpro.github.io/contributing/) ask contributors to submit bugfixes and new features as patches ("diff files").  This seems like a particularly antiquated way of accepting contributions.  Now that we're on GitHub, surely it would be better to ask for pull requests instead?  Is there a reason we still prefer patches, or should the contribution instructions be revised?

**Comment by reckart** [comment]
Yes, that should be updated.
